recipe: "classification/v1"
target_col: "StartHesitation"
positive_class: "1"
primary_metric: "f1_score"
steps:
  ingest: {{INGEST_CONFIG}}
  split:
    using: "custom"
    split_method: custom_split
  transform:
    using: "custom"
    transformer_method: transformer_fn
  train:
    using: "custom"
    estimator_method: estimator_fn
    estimator_params:
      max_epochs: 10
    predict_scores_for_all_classes: True
    predict_prefix: "predicted_"
    tuning:
      enabled: False
  evaluate:
    validation_criteria:
      metric: f1_score
      threshold: 0.5
  register:
    allow_non_validated_model: false